## usage: dlReport
##
## Generate a Markdown report document from stored aggregated data.
##
## The function loads aggregated data from CSV files, creates a report
## directory, generates Markdown report sections from templates, and
## produces the associated charts.
##
## Input data are loaded from the following subdirectories:
##     rewards/data.csv
##     deltas/data.csv
##     critic/data.csv
##     move/data.csv
##     head/data.csv
##
## The generated report contains:
##     - Statistical summaries generated by printReport().
##     - Line plots generated by linplot().
##     - Optional base-10 logarithmic representation for selected
##       statistical reports.
##
## Example:
##
##  dlReport

clear all;

function Y = trendString(regression)
  if regression(2) >= regression(1)
    Y = "increasing";
  else
    Y = "decreasing";
  endif
endfunction

dataPath = "D:/wheelly-data/csv/";
dateStr = strftime("%Y%m%d%H%M", localtime(time ()));
reportPath = ["../reports/" dateStr "/"]
filename = [reportPath, "/report-" dateStr ".md"]
mkdir(reportPath);
hFile = fopen(filename, "w");

# Writes the header section
fprintf(hFile, "# Reinforcement Learning Training Report\n");
fprintf(hFile, "\n");
fprintf(hFile, "Generated on: **%s**\n", strtrim(strftime("%e %B %Y, %R", localtime(time ()))));
fprintf(hFile, "- **Data folder:** `%s`\n", dataPath);
fprintf(hFile, "- **Report folder:** `%s`\n", reportPath);

fprintf(hFile, "\n");
fprintf(hFile, "[TOC]\n");

# Definitions
importFile(hFile, "templates/defs.md");

# Rewards report

rewards = csvread([dataPath "rewards/data.csv"]);
rewardsReg = csvread([dataPath "rewards_reg/data.csv"]);
printReport(hFile, rewards, rewardsReg, "templates/rewardReport.md", "Rewards", reportPath, "rewards.png");

# Deltas report

deltas = csvread([dataPath "deltas/data.csv"]);
deltasReg = csvread([dataPath "deltas_reg/data.csv"]);
printReport(hFile, deltas, deltasReg, "templates/deltaReport.md", "Deltas", reportPath, "deltas.png");

# Critic report

critic = csvread([dataPath "critic/data.csv"]);
criticReg = csvread([dataPath "critic_reg/data.csv"]);
printReport(hFile, critic, criticReg, "templates/criticReport.md", "Critic", reportPath, "critic.png");

# Move report

movePolicy = csvread([dataPath "move/data.csv"]);
movePolicyReg = csvread([dataPath "move_reg/data.csv"]);
printReport(hFile, movePolicy, movePolicyReg, "templates/moveReport.md", "Move action", reportPath, "move.png", true);
printReport(hFile, movePolicy(:, [1, 6 : 9]), movePolicyReg(3 : 4), "templates/moveEntropyReport.md", "Move Policy Entropy",reportPath, "moveEntropy.png");

# Head report
headPolicy = csvread([dataPath "head/data.csv"]);
headPolicyReg = csvread([dataPath "head_reg/data.csv"]);
printReport(hFile, headPolicy, headPolicyReg, "templates/headReport.md", "Head action", reportPath,"head.png", true);
printReport(hFile, headPolicy(:, [1, 6 : 9]), headPolicyReg(3 : 4), "templates/headEntropyReport.md", "Head Policy Entropy", reportPath, "headEntropy.png");

# Summary

importFile(hFile, "templates/summary.md");

fprintf(hFile, "- Reward trend: %s\n", trendString(rewardsReg));
fprintf(hFile, "- Critic value trend: %s\n", trendString(criticReg));
fprintf(hFile, "- Move policy entropy trend: %s\n", trendString(movePolicyReg(3 : 4)));
fprintf(hFile, "- Head policy entropy trend: %s\n", trendString(headPolicyReg(3 : 4)));

fclose(hFile);
