/*
 * Copyright (c) 2026 Marco Marini, marco.marini@mmarini.org
 *
 *  Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 *    END OF TERMS AND CONDITIONS
 *
 */

package org.mmarini.wheelly.fsm;

import org.mmarini.wheelly.apis.RobotCommands;

import static java.util.Objects.requireNonNull;

/**
 * Represents a concrete FSM substate that performs a sequential scan by rotating
 * the robot's head through an array of angular degrees.
 * <p>
 * This state transitions the head through multiple predefined angles, holding each
 * orientation for a fixed scan interval. It tracks the step execution and, upon
 * completion of the final angular target, bubbles a completion event up to the
 * parent superstate to coordinate hierarchical transition <b>behaviour</b>.
 * </p>
 */
public class HeadScanSubState extends AbstractCommitmentState {

    /** The temporal duration in milliseconds allocated to each individual scan step. */
    private final long scanInterval;

    /** The array of target angles in degrees through which the head will rotate. */
    private final int[] headDeg;

    /** Flag tracking whether the entire scanning sequence has been executed. */
    private boolean completed;

    /** The robot timestamp recorded at the beginning of the current step interval. */
    private long startStepTime;

    /** The index pointing to the active target angle within the scan sequence. */
    private int currentStepIndex;

    /**
     * Constructs a {@code HeadScanSubState} with the specified commitment instant,
     * step interval duration, and sequence of target head degrees.
     *
     * @param commitmentInstant the timestamp utilised to evaluate state expiration
     * @param scanInterval      the time duration allocated to each individual angle look
     * @param headDeg           the sequence of target head directions in degrees, must contain at least one element
     * @throws NullPointerException     if the {@code headDeg} array is null
     * @throws IllegalArgumentException if the {@code headDeg} array contains no elements
     */
    public HeadScanSubState(long commitmentInstant, long scanInterval, int... headDeg) {
        super(commitmentInstant);
        this.headDeg = requireNonNull(headDeg);
        if (headDeg.length < 1) {
            throw new IllegalArgumentException("headDeg must have at least one element");
        }
        this.scanInterval = scanInterval;
        currentStepIndex = -1;
    }

    /**
     * Indicates whether the entire head scanning sequence has successfully reached completion.
     *
     * @return true if all scheduled angles have been fully executed; false otherwise
     */
    @Override
    public boolean completed() {
        return completed;
    }

    /**
     * Executes the sequential scanning logic for the current execution tick.
     * <p>
     * This method will <b>initialise</b> the step markers on its first run. On subsequent ticks,
     * it monitors the elapsed robot time to shift indexes to the next target angle. Once the
     * final degree entry expires, it updates its completion flag and bubbles an
     * {@link EnvironmentFSMEvent#COMPLETED} signal up to the active superstate.
     * </p>
     *
     * @param event   the incoming {@link EnvironmentFSMEvent} triggering this execution step
     * @param context the {@link EnvironmentFSMContext} tracking the shared operational data
     * @return the {@link RobotCommands} restricting execution to the active head target angle,
     *         or delegation commands generated by the parent state upon sequence completion
     */
    @Override
    protected RobotCommands execute(EnvironmentFSMEvent event, EnvironmentFSMContext context) {
        long time = context.worldModel().robotStatus().robotTime();
        if (currentStepIndex == -1) {
            // Initialise current action
            currentStepIndex = 0;
            startStepTime = time;
        }
        if (time >= startStepTime + scanInterval) {
            // Scan interval elapsed
            if (currentStepIndex < headDeg.length - 1) {
                // Next scan
                currentStepIndex++;
                startStepTime = time;
            } else {
                completed = true;
                return context.handle(EnvironmentFSMEvent.COMPLETED);
            }
        }
        // Handles commitment interval
        return RobotCommands.halt(headDeg[currentStepIndex]);
    }
}