/*
 * Copyright (c) 2026 Marco Marini, marco.marini@mmarini.org
 *
 *  Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 *    END OF TERMS AND CONDITIONS
 *
 */

package org.mmarini.wheelly.envs;

import org.mmarini.wheelly.apis.RobotCommands;
import org.mmarini.wheelly.apis.WorldModel;

/**
 * An abstract base class for macro-actions that require a time-based commitment.
 * <p>
 * This action remains committed until the current robot time reaches a specified
 * expiration instant. It implements a template method pattern for action execution.
 * </p>
 *
 * @author Marco Marini
 * @version 2026
 */
public abstract class AbstractCommitmentAction implements MacroAction {
    private final long commitmentInstant;
    private long currentTime;

    /**
     * Constructs an AbstractCommitmentAction with a specific commitment expiration instant.
     *
     * @param commitmentInstant the timestamp (in robot time) until which the action remains committed
     */
    protected AbstractCommitmentAction(long commitmentInstant) {
        this.commitmentInstant = commitmentInstant;
    }

    /**
     * Returns the commitment expiration instant.
     *
     * @return the timestamp (in robot time) until which the action remains committed
     */
    public long commitmentInstant() {
        return commitmentInstant;
    }

    /**
     * Checks if the action is still committed based on the last recorded robot time.
     *
     * @return {@code true} if the current robot time is strictly less than the commitment instant;
     * {@code false} otherwise
     */
    @Override
    public boolean committed() {
        return currentTime < commitmentInstant;
    }

    /**
     * Returns the last recorded robot time.
     *
     * @return the current robot time tracked during the last execution cycle
     */
    public long currentTime() {
        return currentTime;
    }

    /**
     * Updates the current tracked time from the world model and delegates the actual
     * command generation to {@link #executeAction(MacroActionContext, WorldModel)}.
     *
     * @param context the macro-action context
     * @param state   the current world model state
     * @return the robot commands generated by this action
     */
    @Override
    public RobotCommands execute(MacroActionContext context, WorldModel state) {
        currentTime = state.robotStatus().robotTime();
        return executeAction(context, state);
    }

    /**
     * Defines the concrete behaviour of the action to generate the robot commands.
     * This method is invoked during the execution cycle after updating the current time.
     *
     * @param context the macro-action context
     * @param state   the current world model state
     * @return the generated {@link RobotCommands}
     */
    protected abstract RobotCommands executeAction(MacroActionContext context, WorldModel state);
}